### ISSUE TITLE
pip install -r requirements.txt fails

### ISSUE THREAD

**Issue by uishon** [Sefaria/Sefaria-Project#645]
Getting this error (on ubuntu 20.04, python 3.8.5)
```
Collecting django_mobile==0.3.0
  Using cached django-mobile-0.3.0.tar.gz (18 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/uri/.virtualenvs/sefaria/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4n8r0sl1/django-mobile_d282a0ade4b84d32983dd8bd42cdf257/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4n8r0sl1/django-mobile_d282a0ade4b84d32983dd8bd42cdf257/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5h78qsrx
         cwd: /tmp/pip-install-4n8r0sl1/django-mobile_d282a0ade4b84d32983dd8bd42cdf257/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4n8r0sl1/django-mobile_d282a0ade4b84d32983dd8bd42cdf257/setup.py", line 47, in <module>
        file('README.rst', 'r').read().decode('utf-8'),
    NameError: name 'file' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by nsantacruz** [comment]
I see pip is trying to install `django_mobile==0.3.0` but our requirements.txt specifies 0.7.0.
Maybe you haven't pulled the repo in a while?

**Comment by uishon** [comment]
Oops. You're right. That was, indeed, my issue. Thanks.
